from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional, Literal

# ---------------------------------------------------------
# GeoJSON Base Models (Standardized Input/Output)
# ---------------------------------------------------------
class GeoJSONGeometry(BaseModel):
    type: str = Field(..., description="E.g., 'Polygon', 'MultiPolygon'")
    coordinates: List[Any] = Field(..., description="Standard RFC 7946 coordinate arrays")

class GeoJSONFeature(BaseModel):
    type: Literal["Feature"] = "Feature"
    geometry: GeoJSONGeometry
    properties: Dict[str, Any] = Field(default_factory=dict)

class GeoJSONFeatureCollection(BaseModel):
    type: Literal["FeatureCollection"] = "FeatureCollection"
    features: List[GeoJSONFeature]

# ---------------------------------------------------------
# Generation Request Payload
# ---------------------------------------------------------
class GenerationRequest(BaseModel):
    # 1. Base Geometry
    site_polygon: GeoJSONFeature = Field(
        ..., 
        description="The master boundary of the development site."
    )
    obstacles: Optional[GeoJSONFeatureCollection] = Field(
        None, 
        description="Existing buildings, lakes, or protected areas to avoid."
    )

    # 2. Kinematic Growth Parameters (Phase 1 & 2)
    target_node_count: int = Field(
        100, 
        ge=10, 
        le=5000, 
        description="The total number of intersections to spawn before stopping."
    )
    max_valency: int = Field(
        4, 
        ge=2, 
        le=6, 
        description="Maximum number of streets connecting to a single intersection."
    )
    major_node_ratio: float = Field(
        0.2, 
        ge=0.0, 
        le=1.0, 
        description="Probability (0-1) of a new node being a Major Arterial vs Minor Local."
    )
    arterial_length: float = Field(
        150.0, 
        gt=0.0, 
        description="Hooke's Law resting length (meters) for Major-to-Major street springs."
    )
    local_length: float = Field(
        60.0, 
        gt=0.0, 
        description="Hooke's Law resting length (meters) for Minor local street springs."
    )
    cross_link_probability: float = Field(
        0.8, 
        ge=0.0, 
        le=1.0, 
        description="Chance to weave branches together into 3-5 edge urban blocks."
    )
    freezing_age_threshold: int = Field(
        20, 
        ge=1, 
        description="How many simulation ticks before a hot node locks its coordinates (Historical Freezing)."
    )

    # 3. Void Resolution Parameters (Phase 4)
    void_resolution_strategy: Literal["parks", "delaunay", "mixed"] = Field(
        "mixed", 
        description="How to handle massive >5 edge blocks created by valency limits."
    )
    park_ratio: float = Field(
        0.3, 
        ge=0.0, 
        le=1.0, 
        description="If strategy is 'mixed', the probability a void becomes a Park vs Delaunay Subdivided."
    )

    # 4. Geometry Translation (Phase 5)
    arterial_width: float = Field(
        12.0, 
        gt=0.0, 
        description="The physical buffer width (meters) of major arterial streets."
    )
    local_width: float = Field(
        6.0, 
        gt=0.0, 
        description="The physical buffer width (meters) of minor local streets."
    )

# ---------------------------------------------------------
# Generation Response Payload
# ---------------------------------------------------------
class GenerationResponse(BaseModel):
    blocks: GeoJSONFeatureCollection = Field(
        ..., 
        description="The final urban blocks generated by subtracting streets from the site."
    )
    streets: GeoJSONFeatureCollection = Field(
        ..., 
        description="The actual street network polygons (useful for visualization or asphalt ML layers)."
    )
    metadata: Dict[str, Any] = Field(
        ..., 
        description="Generation stats (e.g., compute time, total blocks generated, total parks)."
    )
